name: Build font and specimen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install ttfautohint
      run: |
        sudo apt-get update
        sudo apt-get install ttfautohint
    - uses: actions/cache@v2
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Do first-run script if necessary
      run: make .init.stamp
      if: github.repository != 'googlefonts/Unified-Font-Repository'
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: First-run setup
      if: github.repository != 'googlefonts/Unified-Font-Repository'
      with:
        file_pattern: .init.stamp README.md
    - name: Build font
      run: make build
    - name: Check with fontbakery
      run: make test
      continue-on-error: true
    - name: Generate proofs
      run: make proof
    - name: Make release branch
      run: |
          git fetch --depth=1
          # overwrite existing release branch
          git checkout -B release
          # delete everything apart from the fonts/ dir
          find . ! -name 'fonts' -exec rm -f {} +
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit release branch
      with:
        branch: release
        file_pattern: fonts
    
#    - name: Publish site
#      run: |
#        git checkout -f gh-pages
#        # overwrite the fonts/ dir with the release branch
#        rm -rf fonts/
#        git checkout release fonts/
#    
#    - uses: stefanzweifel/git-auto-commit-action@v4
#      name: Commit to gh-pages
#      with:
#        branch: gh-pages
#        file_pattern: fonts *.html badges
#    - name: Archive artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: Artifacts
#        path: |
#          fonts
#          *.html
#          fontbakery-report.md
#