name: Build font and specimen

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install sys tools/deps
      run: |
        sudo apt-get update
        sudo apt-get install ttfautohint
        sudo snap install yq
    - uses: actions/cache@v2
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Do first-run script if necessary
      run: make .init.stamp
      if: github.repository != 'googlefonts/Unified-Font-Repository'
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: First-run setup
      if: github.repository != 'googlefonts/Unified-Font-Repository'
      with:
        file_pattern: .init.stamp README.md

      # Use the release tag in order to bump the fonts
    - name: Bump release
      if: github.event_name == 'release'
      run: |
        FONTS=$(yq e ".sources[]" sources/config.yaml)
        TAG_NAME=${GITHUB_REF/refs\/tags\//}
        echo "Bumping $FONTS $TAG_NAME"
      # bumpfontversion $FONTS --new-version 1.111 

    - name: Build font
      run: make build
    - name: Check with fontbakery
      run: make test
      continue-on-error: true
    - name: proof
      run: make proof
    - name: setup site
      run: cp scripts/index.html out/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: font-assets
        path: |
          fonts
          out
  release:
    # only run if the commit is tagged...
    if: github.event_name == 'release'
    # ... and it builds successfully
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gen dir name
        shell: bash
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
      - name: Download artefact files
        uses: actions/download-artifact@v2
        with:
          name: font-assets
          path: ${{ env.REPOSITORY_NAME }}
      - name: Zip files
        run: zip -r ${{ env.REPOSITORY_NAME }}-fonts.zip ${{ env.REPOSITORY_NAME }}/fonts/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.REPOSITORY_NAME }}-fonts.zip
          asset_name: ${{ env.REPOSITORY_NAME }}-fonts.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "Production ready fonts"