name: Build font and specimen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install ttfautohint
      run: |
        sudo apt-get update
        sudo apt-get install ttfautohint
    - uses: actions/cache@v2
      with:
        path: ./venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-
    - name: Do first-run script if necessary
      run: make .init.stamp
      if: github.repository != 'googlefonts/Unified-Font-Repository'
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: First-run setup
      if: github.repository != 'googlefonts/Unified-Font-Repository'
      with:
        file_pattern: .init.stamp README.md
    - name: Build font
      run: make build
    - name: Check with fontbakery
      run: make test
      continue-on-error: true
    - name: Generate proofs
      run: make proof
    - name: Package
      run: |
        git fetch --depth=1
        git add fonts/ reports/ test_docs/
        git commit -m 'Generated binary assets'
        git checkout -f gh-pages
        rm -rf fonts/ tests/
        git checkout main fonts/ reports/ test_docs/
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit to gh-pages
      with:
        branch: gh-pages
        file_pattern: fonts/* reports/* test_docs/*
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          fonts
          reports
          test_docs
